repos:

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
        always_run: true
        pass_filenames: false
        args: [.]